buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // KSP plugin - version phai khop chinh xac voi Kotlin version
        // Format: <kotlin-version>-<ksp-release>, xem: github.com/google/ksp/releases
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.1.0-1.0.29"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
